CREATE ROLE houmuser WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:qjD4SIb8my0nTB9wPxzzlQ==$iyzRG14o2X3sk+/EOZQPTsPWHkZCEATf+++8RQ+udyc=:QLqb9TgKLDJWO+hpEfCA2AAl/6tqott8SPkwznff8+8=';

CREATE DATABASE houm
WITH
OWNER = houmuser
ENCODING = 'UTF8'
LC_COLLATE = 'C'
LC_CTYPE = 'C'
TABLESPACE = pg_default
CONNECTION LIMIT = -1;