# Generated by Django 3.0.8 on 2022-04-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houmer_id', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('last_updated_on', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
        ),
    ]
